<#
.SYNOPSIS
    Build script: combines the three trivia JSON files into a single data.js
    that the browser front-end can load directly from disk (file://).

.DESCRIPTION
    Browsers block fetch() from file:// URLs, so we cannot load the JSON files
    via XHR when running the app by double-clicking index.html. Instead, this
    script reads all three JSON files and emits a data.js file that assigns
    the combined array to window.TRIVIA_DATA.

    Run this any time you edit one of the source JSON files.

.NOTES
    Per project convention: verbose, timestamped logging to both console
    and a persistent log file.
#>

$ErrorActionPreference = 'Stop'

# ---------- LOGGING ----------
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$LogPath   = Join-Path $ScriptDir 'build_data.log'

function Write-Log {
    param(
        [Parameter(Mandatory)] [ValidateSet('INFO','WARN','ERROR','OK')] [string]$Level,
        [Parameter(Mandatory)] [string]$Message
    )
    $ts   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'
    $line = "[$ts] [$Level] $Message"
    Write-Host $line
    Add-Content -Path $LogPath -Value $line -Encoding UTF8
}

Write-Log INFO '=================================================='
Write-Log INFO '  build_data.ps1 starting'
Write-Log INFO "  Script dir: $ScriptDir"
Write-Log INFO "  Log file:   $LogPath"
Write-Log INFO '=================================================='

# ---------- INPUTS ----------
$Inputs = @(
    @{ File = 'tng_trivia.json'; Series = 'TNG' },
    @{ File = 'ds9_trivia.json'; Series = 'DS9' },
    @{ File = 'voy_trivia.json'; Series = 'VOY' }
)

$All     = New-Object System.Collections.ArrayList
$Skipped = 0

foreach ($entry in $Inputs) {
    $path = Join-Path $ScriptDir $entry.File
    Write-Log INFO "Reading $($entry.Series) from $($entry.File)"

    if (-not (Test-Path -LiteralPath $path)) {
        Write-Log ERROR "  File not found: $path"
        $Skipped++
        continue
    }

    try {
        $raw  = Get-Content -LiteralPath $path -Raw -Encoding UTF8
        $data = $raw | ConvertFrom-Json
    } catch {
        Write-Log ERROR "  Failed to parse $($entry.File): $($_.Exception.Message)"
        $Skipped++
        continue
    }

    if (-not $data) {
        Write-Log WARN  "  $($entry.File) parsed to null/empty — skipping"
        $Skipped++
        continue
    }

    $count = @($data).Count
    Write-Log OK    "  Loaded $count $($entry.Series) question(s)"
    foreach ($q in $data) { [void]$All.Add($q) }
}

Write-Log INFO "Total questions assembled: $($All.Count)"
Write-Log INFO "Files skipped due to errors: $Skipped"

if ($All.Count -eq 0) {
    Write-Log ERROR 'No questions assembled — aborting before writing data.js'
    exit 1
}

# ---------- WRITE data.js ----------
$OutPath = Join-Path $ScriptDir 'data.js'
Write-Log INFO "Writing data.js to: $OutPath"

# ConvertTo-Json with sufficient depth; compact to keep the file small but readable.
$json = $All | ConvertTo-Json -Depth 10 -Compress

$header = @'
// =====================================================================
// data.js — auto-generated by build_data.ps1
// Do not edit by hand. Edit the source *_trivia.json files and re-run
// the build script (PowerShell: .\build_data.ps1).
// =====================================================================
'@

$body = "window.TRIVIA_DATA = $json;"

$contents = "$header`r`n$body`r`n"
Set-Content -LiteralPath $OutPath -Value $contents -Encoding UTF8

$fileSize = (Get-Item -LiteralPath $OutPath).Length
Write-Log OK   "Wrote $fileSize bytes to data.js"
Write-Log INFO '=================================================='
Write-Log OK   '  build_data.ps1 complete'
Write-Log INFO '=================================================='
